### ISSUE TITLE
Create Page Styles for Snapshot

### ISSUE THREAD

**Issue by chair28980** [ShenaniganDApp/docs#18]
Docs: https://docs.snapshot.org/spaces/add-skin

Create Shenanigan themed page stylings for https://snapshot.org/#/shedapp.eth

Reference Design docs (need link) for exact colors and styles.

**Comment by youngkidwarrior** [comment]
@chair28980 the snapshot issue should go in operations. Docs is just for writing

**Comment by chair28980** [comment]
Moved to this board:

https://app.zenhub.com/workspaces/shenanigan-605a78c794095d001a527c29/issues/shenanigandapp/design/4

**Comment by cheo0202** [comment]
Hi
